const String DATABASE_VALESIM = 'gerenciador_transportes';

const String USUARIO_TABLE_NAME = 'usuario';
const String USUARIO_COLUMN_ID = 'id_usuario';
const String USUARIO_COLUMN_NOME = 'nome';
const String USUARIO_COLUMN_SOBRENOME = 'sobrenome';
const String USUARIO_COLUMN_EMAIL = 'email';
const String USUARIO_COLUMN_SENHA = 'senha';

const String CREATE_USUARIO_TABLE_SCRIPT = '''
CREATE TABLE $USUARIO_TABLE_NAME(
  $USUARIO_COLUMN_ID INTEGER PRIMARY KEY,
  $USUARIO_COLUMN_NOME TEXT,
  $USUARIO_COLUMN_SOBRENOME TEXT,
  $USUARIO_COLUMN_EMAIL TEXT,
  $USUARIO_COLUMN_SENHA TEXT
)''';

const String TRANSPORTE_TABLE_NAME = 'transporte';
const String TRANSPORTE_COLUMN_ID = 'id_transporte';
const String TRANSPORTE_COLUMN_NOME = 'nome';
const String TRANSPORTE_COLUMN_RENAVAM = 'renavam';
const String TRANSPORTE_COLUMN_PLACA = 'placa';
const String TRANSPORTE_COLUMN_CAPACIDADE = 'capacidade';
const String TRANSPORTE_COLUMN_LINHA = 'linha';

const String CREATE_TRANSPORTE_TABLE_SCRIPT = '''
CREATE TABLE $TRANSPORTE_TABLE_NAME(
  $TRANSPORTE_COLUMN_ID INTEGER PRIMARY KEY,
  $TRANSPORTE_COLUMN_NOME TEXT,
  $TRANSPORTE_COLUMN_RENAVAM TEXT,
  $TRANSPORTE_COLUMN_PLACA TEXT,
  $TRANSPORTE_COLUMN_CAPACIDADE TEXT,
  $TRANSPORTE_COLUMN_LINHA TEXT
)''';