const String DATABASE_VALESIM = 'gerenciador_transportes';

const String USUARIO_TABLE_NAME = 'usuario';
const String USUARIO_COLUMN_ID = 'id_usuario';
const String USUARIO_COLUMN_NOME = 'nome';
const String USUARIO_COLUMN_SOBRENOME = 'sobrenome';
const String USUARIO_COLUMN_EMAIL = 'email';
const String USUARIO_COLUMN_SENHA = 'senha';

const String CREATE_USUARIO_TABLE_SCRIPT = '''
CREATE TABLE $USUARIO_TABLE_NAME(
  $USUARIO_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  $USUARIO_COLUMN_NOME TEXT,
  $USUARIO_COLUMN_SOBRENOME TEXT,
  $USUARIO_COLUMN_EMAIL TEXT,
  $USUARIO_COLUMN_SENHA TEXT
)''';

const String TRANSPORTE_TABLE_NAME = 'transporte';
const String TRANSPORTE_COLUMN_ID = 'id_transporte';
const String TRANSPORTE_COLUMN_NOME = 'nome';
const String TRANSPORTE_COLUMN_RENAVAM = 'renavam';
const String TRANSPORTE_COLUMN_NUMERO = 'numero';
const String TRANSPORTE_COLUMN_PLACA = 'placa';
const String TRANSPORTE_COLUMN_FAVORITO = 'favorito';
const String TRANSPORTE_COLUMN_CAPACIDADE = 'capacidade';
const String TRANSPORTE_COLUMN_LINHA = 'linha';

const String CREATE_TRANSPORTE_TABLE_SCRIPT = '''
CREATE TABLE $TRANSPORTE_TABLE_NAME(
  $TRANSPORTE_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  $TRANSPORTE_COLUMN_NOME TEXT,
  $TRANSPORTE_COLUMN_RENAVAM TEXT,
  $TRANSPORTE_COLUMN_NUMERO TEXT,
  $TRANSPORTE_COLUMN_PLACA TEXT,
  $TRANSPORTE_COLUMN_CAPACIDADE TEXT,
  $TRANSPORTE_COLUMN_FAVORITO INTEGER,
  $TRANSPORTE_COLUMN_LINHA TEXT
)''';

const String FAVORITO_TABLE_NAME = 'favorito';
const String FAVORITO_COLUMN_ID = 'id_favorito';
const String FAVORITO_COLUMN_USUARIO_ID = 'id_usuario';
const String FAVORITO_COLUMN_TRANSPORTE_ID = 'id_transporte';

const String CREATE_FAVORITO_TABLE_SCRIPT = '''
 CREATE TABLE $FAVORITO_TABLE_NAME (
  $FAVORITO_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  $FAVORITO_COLUMN_USUARIO_ID INTEGER,
  $FAVORITO_COLUMN_TRANSPORTE_ID INTEGER,
  FOREIGN KEY ($FAVORITO_COLUMN_USUARIO_ID) REFERENCES $USUARIO_TABLE_NAME($USUARIO_COLUMN_ID),
  FOREIGN KEY ($FAVORITO_COLUMN_TRANSPORTE_ID) REFERENCES $TRANSPORTE_TABLE_NAME($TRANSPORTE_COLUMN_ID)
)''';